### ISSUE TITLE
"Done" button doesn't appear in the web version

### ISSUE THREAD

**Issue by iamkarlson** [hvxl/otmonitor#10]
Hi, I've built otmonitor using this manual http://otgw.tclcode.com/otmonsrc.html and "done" button doesn't appear on "Configure" page as well as settings Gateway/Monitor not being set. Is there troubleshooting guidance on why it can happen? 

![image](https://user-images.githubusercontent.com/4534374/94069719-57c9a580-fdf1-11ea-9fd5-9d6a8292fcf1.png)

**Comment by hvxl** [comment]
There is no "Done" button because there isn't supposed to be one. In the GUI, the "Done" button closes the window. As of 2017, there is no way to close a web browser tab or window using JavaScript. Modern security standards do not permit this behavior. So the available choices were: Have a non-functional "Done" button, or not have a "Done" button at all. The latter option seemed the better choice to me.

When you access the Miscellaneous configuration page and the Operating mode is Unknown, OTmonitor sends a PR=M command to the OTGW. The page is updated when the response is received. If the mode remains "Unknown", it means that either no response was received, or the websocket connection was lost. I suggest to check the message log to verify what is going on.
